//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableSchemaExporter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TableSchemaExporter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    c.name AS &apos;Column Name&apos;,
        ///    t.Name AS &apos;Data type&apos;,
        ///    c.max_length AS &apos;Max Length&apos;,
        ///    c.precision AS &apos;Precision&apos;,    
        ///    c.is_nullable AS &apos;Is Nullable&apos;,
        ///    ISNULL(i.is_primary_key, 0) AS &apos;Primary Key&apos;
        ///FROM    
        ///    sys.columns c
        ///INNER JOIN 
        ///    sys.types t ON c.system_type_id = t.system_type_id AND t.system_type_id = t.user_type_id
        ///LEFT OUTER JOIN 
        ///    sys.index_columns ic ON ic.object_id = c.object_id AND ic.column_id = c.column_id
        ///LEFT OUTER JOIN 
        ///    sys.indexes i ON ic.obj [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string select_table_schema_query {
            get {
                return ResourceManager.GetString("select_table_schema_query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &apos;[&apos;+SCHEMA_NAME(schema_id)+&apos;].[&apos;+name+&apos;]&apos;
        ///AS SchemaTable
        ///FROM sys.tables
        ///ORDER BY schema_id ASC;.
        /// </summary>
        internal static string select_tables_query {
            get {
                return ResourceManager.GetString("select_tables_query", resourceCulture);
            }
        }
    }
}
